### ISSUE TITLE
uninitialized constant Learn::InternetConnection::OpenSSL

### ISSUE THREAD

**Issue by pletcher** [learn-co/learn-co#71]
A student running `learn hello` ran into this issue: 

`/Users/ambikadubey/.rvm/gems/ruby-2.2.4/gems/learn-co-3.4.0/lib/learn/internet_connection.rb:60:in 'rescue in test_connection': uninitialized constant Learn::InternetConnection::OpenSSL (NameError)`

Source: https://app.intercom.io/a/apps/j4d6dyie/inbox/conversation/4372241254

**Comment by loganhasson** [comment]
fixed by b2b85b89d1eaa5177f5cb3296e40ee93872d9395
