### ISSUE TITLE
Progress is not visible on the site

### ISSUE THREAD

**Issue by michaelbukachi** [learn-co/learn-co#76]
The progress of my lesson is not updated on the website. You can see it below:
![screenshot from 2017-06-28 12-33-52](https://user-images.githubusercontent.com/10145850/27630521-6d3f04b6-5bfe-11e7-8028-6fb4eba191c5.png)

**Comment by gj** [comment]
Hi there,

Check out [this article about lights not turning green](http://help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) in the [Learn Help Center](http://help.learn.co/).

Thanks! 💙
